language: python
python:
  - "2.7"

before_install:
  - pip install --upgrade supervisor
  - sudo curl https://raw.githubusercontent.com/illagrenan/ubuntu-supervisor-configuration/master/supervisor.sh > supervisor.sh
  - sudo chmod +x supervisor.sh
  - mkdir -p /etc/supervisor/
  - sudo curl https://raw.githubusercontent.com/illagrenan/ubuntu-supervisor-configuration/master/supervisord.conf > /etc/supervisor/supervisord.conf

script:
  - ./supervisor.sh status

notifications:
  email:
    on_success: never
    on_failure: never
